# Use Node.js official image as a base
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install Expo CLI globally
RUN npm install expo@52
# Install Expo CLI globally
RUN npm install -g expo@52 @expo/ngrok

# Expose the default Expo port
EXPOSE 19000
EXPOSE 19001
EXPOSE 19002
EXPOSE 8081
EXPOSE 8082

# Start the Expo server
CMD ["npx", "expo", "start", "--tunnel"]